# Generated by Django 3.1.7 on 2021-03-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('tel_number', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
